"""
main.py — Campana
-----------------
Generative bell synthesizer.

Usage:
    python main.py --list                          # list presets
    python main.py                                 # export default preset (sera, 2 min)
    python main.py --preset tempio                 # export one preset
    python main.py --preset sera --minutes 5       # 5-minute export
    python main.py --all                           # export all presets + freesound xlsx
    python main.py --all --minutes 2               # all presets, 2 min each
    python main.py --preset sera --freesound       # single preset + freesound row
    python main.py --gui                           # launch web UI

    # Individual bell note samples (24-bit WAV, suitable as instrument samples):
    python main.py --samples                       # all textures × C2-B5 (192 files)
    python main.py --samples --sample-textures tubular church
    python main.py --samples --sample-octaves 3 4 5
    python main.py --samples --sample-notes C D E G A
    python main.py --samples --sample-rate 96000   # 96 kHz high-res
    python main.py --samples --sample-reverb 0.3   # samples with reverb
    python main.py --samples --sample-dir my_samples/
"""

import argparse
import struct
import sys
import numpy as np
from pathlib import Path

EXPORT_DIR = Path("exports")
EXPORT_DIR.mkdir(exist_ok=True)

# ── Per-preset metadata for Freesound upload ──────────────────────────────────
_FREESOUND_META = {
    "sera": {
        "mood_tags": "church-bell bronze dusk evening melancholic warm deep",
        "blurb":     "Dusk church bells with deep reverb and warm, resonant strikes. Dense and contemplative.",
    },
    "tempio": {
        "mood_tags": "tibetan singing-bowl meditation zen buddhist bowl beating slow",
        "blurb":     "Tibetan singing bowl harmonics with massive reverb and slow beating partials that shimmer and breathe.",
    },
    "cristallo": {
        "mood_tags": "crystal glass harmonic bright airy shimmer high-register scattered",
        "blurb":     "Crystal glass harmonics with shimmer, delay, and scattered timing. Airy and ethereal.",
    },
    "cattedrale": {
        "mood_tags": "cathedral church-bell bronze toll deep dark slow wide-stereo spacious",
        "blurb":     "Cathedral tolls — the heaviest reverb, slowest pace, and widest stereo field.",
    },
    "deriva": {
        "mood_tags": "floating drift untethered crystal scatter free evolving spatial",
        "blurb":     "Floating, untethered bells with maximum time scatter. Notes drift freely off the grid.",
    },
    "notte": {
        "mood_tags": "dark night low sparse tubular-bell contemplative midnight slow",
        "blurb":     "Dark, low-register tubular bells. Sparse and contemplative — ideal for late hours.",
    },
    "giardino": {
        "mood_tags": "bright joyful tubular-bell major uplifting fast energetic festive",
        "blurb":     "Bright tubular bell arpeggios in C major at 90 BPM. Joyful and energetic.",
    },
    "aurora": {
        "mood_tags": "whole-tone dreamy ambiguous shimmer ascending arc crystal dawn",
        "blurb":     "Whole-tone scale ascending and descending arc. Dreamy, harmonically ambiguous, with shimmer.",
    },
}

_BASE_TAGS = (
    "bell bells generative campana synthesizer ambient procedural "
    "additive-synthesis soundscape meditation relaxation atmospheric evolving "
    "generative-music looping infinite"
)

_BASE_DESCRIPTION = """\
A generative bell soundscape generated by Campana (https://bassimatte.github.io/campana/).

Campana is a browser-based generative bell synthesizer that creates endlessly evolving soundscapes using additive synthesis. Every bell tone is built from scratch — a set of inharmonic partial frequencies characteristic of real bells, summed and shaped with individual amplitude envelopes. No samples, no loops: each render is unique.

Four bell textures are available:
• Tubular — steel tube bells, bright attack
• Church — cast bronze, deep fundamental
• Bowl — Tibetan singing bowls, slowly beating partials
• Crystal — glass harmonics, high shimmer

The effects chain includes Freeverb algorithmic reverb (comb + allpass filters), stereo ping-pong delay, time scatter (detaches notes from the strict grid for a free, floating feel), humanize (micro-variations in timing and velocity), and beating (slight detuning between partials simulating the slow pulsations of real bells).

Notes are generated by an epoch-based random walk over the selected scale — every 16 beats uses a fresh seed, so the music never repeats.

"""

_PRESET_DESCRIPTION_TEMPLATE = """\
--- PRESET: {name} ---
Texture: {texture} | Key: {key} {scale_mode} | BPM: {bpm}

{blurb}"""


import struct


def _write_wav_24bit(audio: np.ndarray, sample_rate: int) -> bytes:
    """Write a stereo float64 array as 24-bit PCM WAV at the given sample rate.
    Normalises to -1 dBFS before encoding.
    """
    peak = np.max(np.abs(audio))
    if peak > 0:
        audio = audio / peak * 0.9089  # -1 dBFS
    # Scale to 24-bit signed integer range and interleave L/R
    pcm = np.clip(audio * 8_388_607, -8_388_608, 8_388_607).astype(np.int32)
    flat = pcm.flatten(order='C')   # interleaved L R L R …

    # Vectorised 24-bit packing: view int32 as 4 bytes, drop MSB (big-endian) or
    # keep bytes 0-2 (little-endian). int32 is already little-endian on x86.
    b4 = flat.view(np.uint8).reshape(-1, 4)   # shape (N, 4), LE order
    data_bytes = b4[:, :3].tobytes()           # keep low 3 bytes → 24-bit LE PCM

    channels    = 2
    bit_depth   = 24
    byte_depth  = 3
    data_size   = len(data_bytes)
    byte_rate   = sample_rate * channels * byte_depth
    block_align = channels * byte_depth

    header = struct.pack('<4sI4s4sIHHIIHH4sI',
        b'RIFF', 36 + data_size, b'WAVE',
        b'fmt ', 16,
        1,            # PCM
        channels,
        sample_rate,
        byte_rate,
        block_align,
        bit_depth,
        b'data', data_size,
    )
    return header + data_bytes


def render_bell_sample(
    note_name: str,
    texture: str = "tubular",
    decay_mult: float = 1.0,
    beating: float = 0.0,
    strike_level: float = 0.0,
    attack_ms: float = 0.0,
    reverb_room: float = 0.0,
    reverb_damping: float = 0.4,
    reverb_width: float = 0.8,
    reverb_wet: float = 0.0,
    velocity: float = 1.0,
    tail_s: float = 1.0,
    sample_rate: int = None,
) -> bytes:
    """Render a single bell note as a 24-bit stereo WAV sample.

    The duration is determined by the texture's longest partial decay
    time × decay_mult, plus a configurable tail silence.
    Returns raw WAV bytes.
    """
    from engine.synth import (
        BELL_TEXTURES, SAMPLE_RATE as _SR,
        bell_tone, freeverb, note_freq,
    )
    sr = sample_rate or _SR
    partials = BELL_TEXTURES.get(texture, BELL_TEXTURES["tubular"])
    max_tau  = max(tau for _, _, tau in partials)
    # Duration long enough for the tone to fully decay to inaudibility
    duration = max_tau * decay_mult * 5.0 + tail_s   # 5τ ≈ -65 dB

    freq = note_freq(note_name)

    # Mono synthesis then spread to stereo
    _MICRO = 0.0007
    left  = bell_tone(freq * (1 + _MICRO), duration, velocity=velocity,
                      decay_mult=decay_mult, texture=texture,
                      attack_ms=attack_ms, beating=beating,
                      strike_level=strike_level)
    right = bell_tone(freq * (1 - _MICRO), duration, velocity=velocity,
                      decay_mult=decay_mult, texture=texture,
                      attack_ms=attack_ms, beating=beating,
                      strike_level=strike_level)

    stereo = np.column_stack([left, right]).astype(np.float64)

    if reverb_wet > 0.005 and reverb_room > 0.0:
        stereo = freeverb(stereo,
                          room_size=reverb_room,
                          damping=reverb_damping,
                          wet=reverb_wet,
                          width=reverb_width)

    return _write_wav_24bit(stereo, sr)


def export_samples(
    textures: list | None = None,
    octaves: list | None = None,
    notes: list | None = None,
    decay_mult: float = 1.0,
    reverb_wet: float = 0.0,
    reverb_room: float = 0.5,
    output_dir: Path = None,
    sample_rate: int = 48_000,
    beating: float = 0.0,
    strike_level: float = 0.0,
):
    """Export one 24-bit WAV sample per (texture, note, octave) combination.

    Files are written to output_dir/<texture>/<note><octave>.wav
    e.g.  samples/tubular/C4.wav
    """
    import numpy as np  # ensure available in scope
    from engine.synth import BELL_TEXTURES, _NOTE_NAMES

    all_textures = list(BELL_TEXTURES.keys())
    all_notes    = _NOTE_NAMES   # chromatic, 12 notes

    textures = textures or all_textures
    octaves  = octaves  or [2, 3, 4, 5]
    notes    = notes    or all_notes

    output_dir = output_dir or (EXPORT_DIR / "samples")

    total = len(textures) * len(notes) * len(octaves)
    done  = 0
    xlsx_rows = []

    print(f"\n🔔  Exporting {total} bell samples  →  {output_dir}/")
    print(f"    Textures : {', '.join(textures)}")
    print(f"    Notes    : {', '.join(notes)}")
    print(f"    Octaves  : {', '.join(str(o) for o in octaves)}")
    print(f"    Format   : 24-bit / {sample_rate // 1000} kHz stereo WAV")
    if reverb_wet > 0:
        print(f"    Reverb   : room={reverb_room:.2f}  wet={reverb_wet:.2f}")
    print()

    for texture in textures:
        t_params = _TEXTURE_SAMPLE_PARAMS.get(texture, {})
        tex_dir = output_dir / texture
        tex_dir.mkdir(parents=True, exist_ok=True)

        for note in notes:
            for octave in octaves:
                note_name = f"{note}{octave}"
                out_path  = tex_dir / f"{note_name}.wav"
                wav = render_bell_sample(
                    note_name,
                    texture       = texture,
                    decay_mult    = t_params.get("decay_mult", decay_mult),
                    beating       = t_params.get("beating", beating),
                    strike_level  = t_params.get("strike_level", strike_level),
                    attack_ms     = t_params.get("attack_ms", 0.0),
                    reverb_wet    = reverb_wet,
                    reverb_room   = reverb_room,
                    sample_rate   = sample_rate,
                )
                out_path.write_bytes(wav)
                done += 1
                dur_s = (len(wav) - 44) / (sample_rate * 2 * 3)
                rel_path = f"{texture}/{note_name}.wav"
                xlsx_rows.append(_sample_freesound_row(texture, note_name, rel_path, dur_s, sample_rate))
                print(f"  [{done:>3}/{total}]  {texture:<10} {note_name:<5}  "
                      f"{dur_s:.1f}s  →  {out_path}")

    xlsx_path = output_dir / "freesound_bulk.xlsx"
    write_freesound_xlsx(xlsx_rows, xlsx_path)
    print(f"\n✅  Done — {total} samples in {output_dir}/")


# Per-texture defaults for sample rendering (tweak per bell family)
_TEXTURE_SAMPLE_PARAMS = {
    "tubular":  {"decay_mult": 1.0, "beating": 0.0,  "strike_level": 0.4, "attack_ms": 0},
    "church":   {"decay_mult": 1.2, "beating": 0.0,  "strike_level": 0.2, "attack_ms": 0},
    "bowl":     {"decay_mult": 1.5, "beating": 0.45, "strike_level": 0.0, "attack_ms": 8},
    "crystal":  {"decay_mult": 1.1, "beating": 0.15, "strike_level": 0.1, "attack_ms": 0},
}

_TEXTURE_BLURB = {
    "tubular":  "Bright, metallic tubular bell with sharp attack and clear overtones.",
    "church":   "Deep cast-bronze church bell with a warm fundamental and long resonance.",
    "bowl":     "Tibetan singing bowl with slowly beating partials and an extended, shimmering decay.",
    "crystal":  "Glass-like crystal bell with high inharmonic partials and a glassy, sustained shimmer.",
}

_TEXTURE_TAGS = {
    "tubular":  "tubular-bell metal bright attack overtone",
    "church":   "church-bell bronze cast-bell deep warm",
    "bowl":     "singing-bowl tibetan meditation beating shimmer",
    "crystal":  "crystal glass bell harmonic shimmer glassy",
}

_CAMPANA_BLURB = (
    "Generated with Campana — a browser-based generative bell synthesizer using additive synthesis "
    "(https://bassimatte.github.io/campana/)."
)


def _sample_freesound_row(texture: str, note_name: str, filename: str,
                          dur_s: float, sample_rate: int) -> dict:
    """Build one Freesound metadata row for a single bell sample file."""
    tex_cap  = texture.capitalize()
    note_num = note_name[-1]        # octave digit
    note_ltr = note_name[:-1]       # note letter(s)

    sound_desc = (
        f"{tex_cap} bell tone — note {note_ltr}, octave {note_num}. "
        f"{_TEXTURE_BLURB[texture]} "
        f"Single note, ~{dur_s:.0f}s natural decay. "
        f"24-bit / {sample_rate // 1000} kHz stereo WAV. Dry (no reverb).\n\n"
        f"{_CAMPANA_BLURB}"
    )

    base_tags = (
        "bell single-note sample instrument one-shot additive-synthesis "
        "campana synthesizer 24bit high-resolution"
    )
    tags = f"{base_tags} {_TEXTURE_TAGS[texture]} {note_ltr.lower()} octave{note_num} {note_ltr}{note_num}"

    return {
        "audio_filename": filename,
        "name":           f"{tex_cap} Bell — {note_ltr}{note_num}",
        "tags":           tags,
        "geotag":         "",
        "description":    sound_desc,
        "license":        "Creative Commons 0",
        "pack_name":      f"Campana Bell Samples — {tex_cap}",
        "is_explicit":    0,
        "bst_category":   "is-e",
    }


def _freesound_row(preset_id: str, filename: str, minutes: float) -> dict:
    from engine.presets import PRESETS
    p    = PRESETS[preset_id]
    meta = _FREESOUND_META.get(preset_id, {"mood_tags": "", "blurb": p.get("description", "")})
    name = p["name"]
    bpm  = p.get("default_bpm", "?")
    key  = p.get("default_key", "C")
    scale= p.get("default_scale_mode", "minor")
    tex  = p.get("default_texture", "tubular")

    tags = f"{_BASE_TAGS} {meta['mood_tags']} {tex} {key.lower()} {scale.replace('_', '-')}".strip()
    desc = _BASE_DESCRIPTION + _PRESET_DESCRIPTION_TEMPLATE.format(
        name=name, texture=tex.capitalize(), key=key, scale_mode=scale.replace("_", " "),
        bpm=bpm, blurb=meta["blurb"],
    )

    return {
        "audio_filename": filename,
        "name":           f"{name} – Generative Bell Soundscape by Campana",
        "tags":           tags,
        "geotag":         "",
        "description":    desc,
        "license":        "Creative Commons 0",
        "pack_name":      "Generative Bells by Campana",
        "is_explicit":    0,
        "bst_category":   "m-m",
    }


def write_freesound_xlsx(rows: list, output: Path):
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Freesound Bulk Describe"

    headers = ["audio_filename", "name", "tags", "geotag", "description",
               "license", "pack_name", "is_explicit", "bst_category"]
    widths  = [32, 52, 80, 12, 80, 22, 30, 12, 14]

    hdr_font = Font(name="Arial", bold=True, color="FFFFFF")
    hdr_fill = PatternFill("solid", start_color="2F5496")
    hdr_al   = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for col, (h, w) in enumerate(zip(headers, widths), 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.font = hdr_font; cell.fill = hdr_fill; cell.alignment = hdr_al
        ws.column_dimensions[cell.column_letter].width = w

    row_al  = Alignment(vertical="top", wrap_text=True)
    alt_fill = PatternFill("solid", start_color="EEF3FB")

    for i, row in enumerate(rows, 2):
        fill = alt_fill if i % 2 == 0 else None
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=i, column=col, value=row.get(h, ""))
            cell.font      = Font(name="Arial", size=10)
            cell.alignment = row_al
            if fill: cell.fill = fill

    ws.row_dimensions[1].height = 22
    for i in range(2, len(rows) + 2):
        ws.row_dimensions[i].height = 80

    ws.freeze_panes = "A2"
    wb.save(output)
    print(f"  📋 Freesound xlsx  →  {output}")


def list_presets():
    from engine.presets import PRESETS
    print(f"{'ID':<16} {'Name':<16} BPM   Key        Scale")
    print("─" * 60)
    for pid, p in PRESETS.items():
        print(f"{pid:<16} {p['name']:<16} {p.get('default_bpm','?'):<6}"
              f"{p.get('default_key','C'):<11}{p.get('default_scale_mode','minor')}")
    print(f"\n{len(PRESETS)} preset(s).")


def render_preset(preset_id: str, minutes: float, output: Path):
    from engine.web_server import _do_full_render, _parse_render_params
    from engine.presets import PRESETS

    preset = PRESETS.get(preset_id)
    if preset is None:
        sys.exit(f"Unknown preset '{preset_id}'. Use --list to see options.")

    p = _parse_render_params({
        "preset":     preset_id,
        "bpm":        preset["default_bpm"],
        "key":        preset.get("default_key", "C"),
        "reverb_room":      preset.get("default_reverb", 0.75),
        "reverb_damping":   preset.get("default_reverb_damping", 0.4),
        "reverb_width":     preset.get("default_reverb_width", 0.8),
        "reverb_wet":       preset.get("default_reverb_wet", 0.35),
        "decay_mult":       preset.get("default_decay", 1.4),
        "texture":          preset.get("default_texture", "tubular"),
        "beating":          preset.get("default_beating", 0.0),
        "strike_level":     preset.get("default_strike", 0.0),
        "attack_ms":        preset.get("default_attack_ms", 0.0),
        "humanize":         preset.get("default_humanize", 0.0),
        "density":          preset.get("default_density", 1.0),
        "octave_spread":    preset.get("default_octave_spread", 0.0),
        "base_octave_shift":preset.get("default_base_octave", 0),
        "time_scatter":     preset.get("default_time_scatter", 0.0),
        "delay_time":       preset.get("default_delay_time", 300),
        "delay_feedback":   preset.get("default_delay_feedback", 0.35),
        "delay_wet":        preset.get("default_delay_wet", 0.0),
        "shimmer":          preset.get("default_shimmer", 0.0),
        "scale_mode":       preset.get("default_scale_mode", "minor"),
        "seed_base":        42,
    })
    p["export_beats"] = minutes * p["bpm"]

    print(f"  🔔 {preset['name']:<14} {minutes:.0f} min @ {p['bpm']} BPM …", end="", flush=True)
    wav = _do_full_render(p)
    output.write_bytes(wav)
    dur = len(wav) / (48_000 * 2 * 2)
    print(f"  {dur/60:.1f} min  →  {output}  ({len(wav)/1e6:.1f} MB)")
    return output.name


def main():
    from engine.presets import PRESETS

    parser = argparse.ArgumentParser(description="Campana — generative bell synthesizer")
    parser.add_argument("--gui",       action="store_true", help="Launch web UI")
    parser.add_argument("--list",      action="store_true", help="List presets")
    parser.add_argument("--all",       action="store_true", help="Export all presets")
    parser.add_argument("--freesound", action="store_true", help="Generate Freesound bulk upload xlsx")
    parser.add_argument("--preset",    default="sera",
                        choices=list(PRESETS.keys()), help="Preset ID (default: sera)")
    parser.add_argument("--minutes",   type=float, default=2.0,
                        help="Export duration in minutes (default: 2)")
    parser.add_argument("--output",    type=Path, default=None,
                        help="Output WAV path (single preset only)")

    # ── Sample export ──────────────────────────────────────────────────────────
    parser.add_argument("--samples",        action="store_true",
                        help="Export individual bell note samples (24-bit WAV)")
    parser.add_argument("--sample-textures", nargs="+",
                        choices=["tubular", "church", "bowl", "crystal"],
                        metavar="TEXTURE",
                        help="Textures to sample (default: all four)")
    parser.add_argument("--sample-octaves",  nargs="+", type=int,
                        metavar="N",
                        help="Octaves to sample (default: 2 3 4 5)")
    parser.add_argument("--sample-notes",    nargs="+",
                        metavar="NOTE",
                        help="Notes to sample, e.g. C D E F G A B (default: all 12)")
    parser.add_argument("--sample-rate",     type=int, default=48_000,
                        choices=[44100, 48000, 88200, 96000],
                        help="Sample rate in Hz (default: 48000)")
    parser.add_argument("--sample-reverb",   type=float, default=0.0,
                        metavar="WET",
                        help="Reverb wet mix for samples 0–1 (default: 0 = dry)")
    parser.add_argument("--sample-dir",      type=Path,
                        default=EXPORT_DIR / "samples",
                        help="Output directory for samples")
    args = parser.parse_args()

    if args.list:
        list_presets()
        return

    if args.gui:
        try:
            from engine.web_server import launch_gui
        except ImportError as e:
            sys.exit(f"Web UI requires fastapi and uvicorn.\nError: {e}")
        launch_gui()
        return

    if args.samples:
        export_samples(
            textures   = args.sample_textures,
            octaves    = args.sample_octaves,
            notes      = args.sample_notes,
            reverb_wet = args.sample_reverb,
            output_dir = args.sample_dir,
            sample_rate= args.sample_rate,
        )
        return

    if args.all:
        print(f"Exporting all {len(PRESETS)} presets ({args.minutes:.0f} min each) → {EXPORT_DIR}/\n")
        rows = []
        for pid in PRESETS:
            fname = render_preset(pid, args.minutes, EXPORT_DIR / f"{pid}.wav")
            rows.append(_freesound_row(pid, fname, args.minutes))
        write_freesound_xlsx(rows, EXPORT_DIR / "freesound_bulk.xlsx")
        print("\nDone.")
    else:
        output = args.output or EXPORT_DIR / f"{args.preset}.wav"
        fname  = render_preset(args.preset, args.minutes, output)
        if args.freesound:
            rows = [_freesound_row(args.preset, fname, args.minutes)]
            write_freesound_xlsx(rows, output.parent / "freesound_bulk.xlsx")


if __name__ == "__main__":
    main()
