"""
main.py — Campana
-----------------
Generative bell synthesizer.

Usage:
    python main.py --list                          # list presets
    python main.py                                 # export default preset (sera, 2 min)
    python main.py --preset tempio                 # export one preset
    python main.py --preset sera --minutes 5       # 5-minute export
    python main.py --all                           # export all presets + freesound xlsx
    python main.py --all --minutes 2               # all presets, 2 min each
    python main.py --preset sera --freesound       # single preset + freesound row
    python main.py --gui                           # launch web UI
"""

import argparse
import sys
from pathlib import Path

EXPORT_DIR = Path("exports")
EXPORT_DIR.mkdir(exist_ok=True)

# ── Per-preset metadata for Freesound upload ──────────────────────────────────
_FREESOUND_META = {
    "sera": {
        "mood_tags": "church-bell bronze dusk evening melancholic warm deep",
        "blurb":     "Dusk church bells with deep reverb and warm, resonant strikes. Dense and contemplative.",
    },
    "tempio": {
        "mood_tags": "tibetan singing-bowl meditation zen buddhist bowl beating slow",
        "blurb":     "Tibetan singing bowl harmonics with massive reverb and slow beating partials that shimmer and breathe.",
    },
    "cristallo": {
        "mood_tags": "crystal glass harmonic bright airy shimmer high-register scattered",
        "blurb":     "Crystal glass harmonics with shimmer, delay, and scattered timing. Airy and ethereal.",
    },
    "cattedrale": {
        "mood_tags": "cathedral church-bell bronze toll deep dark slow wide-stereo spacious",
        "blurb":     "Cathedral tolls — the heaviest reverb, slowest pace, and widest stereo field.",
    },
    "deriva": {
        "mood_tags": "floating drift untethered crystal scatter free evolving spatial",
        "blurb":     "Floating, untethered bells with maximum time scatter. Notes drift freely off the grid.",
    },
    "notte": {
        "mood_tags": "dark night low sparse tubular-bell contemplative midnight slow",
        "blurb":     "Dark, low-register tubular bells. Sparse and contemplative — ideal for late hours.",
    },
    "giardino": {
        "mood_tags": "bright joyful tubular-bell major uplifting fast energetic festive",
        "blurb":     "Bright tubular bell arpeggios in C major at 90 BPM. Joyful and energetic.",
    },
    "aurora": {
        "mood_tags": "whole-tone dreamy ambiguous shimmer ascending arc crystal dawn",
        "blurb":     "Whole-tone scale ascending and descending arc. Dreamy, harmonically ambiguous, with shimmer.",
    },
}

_BASE_TAGS = (
    "bell bells generative campana synthesizer ambient procedural "
    "additive-synthesis soundscape meditation relaxation atmospheric evolving "
    "generative-music looping infinite"
)

_BASE_DESCRIPTION = """\
A generative bell soundscape generated by Campana (https://bassimatte.github.io/campana/).

Campana is a browser-based generative bell synthesizer that creates endlessly evolving soundscapes using additive synthesis. Every bell tone is built from scratch — a set of inharmonic partial frequencies characteristic of real bells, summed and shaped with individual amplitude envelopes. No samples, no loops: each render is unique.

Four bell textures are available:
• Tubular — steel tube bells, bright attack
• Church — cast bronze, deep fundamental
• Bowl — Tibetan singing bowls, slowly beating partials
• Crystal — glass harmonics, high shimmer

The effects chain includes Freeverb algorithmic reverb (comb + allpass filters), stereo ping-pong delay, time scatter (detaches notes from the strict grid for a free, floating feel), humanize (micro-variations in timing and velocity), and beating (slight detuning between partials simulating the slow pulsations of real bells).

Notes are generated by an epoch-based random walk over the selected scale — every 16 beats uses a fresh seed, so the music never repeats.

"""

_PRESET_DESCRIPTION_TEMPLATE = """\
--- PRESET: {name} ---
Texture: {texture} | Key: {key} {scale_mode} | BPM: {bpm}

{blurb}"""


def _freesound_row(preset_id: str, filename: str, minutes: float) -> dict:
    from engine.presets import PRESETS
    p    = PRESETS[preset_id]
    meta = _FREESOUND_META.get(preset_id, {"mood_tags": "", "blurb": p.get("description", "")})
    name = p["name"]
    bpm  = p.get("default_bpm", "?")
    key  = p.get("default_key", "C")
    scale= p.get("default_scale_mode", "minor")
    tex  = p.get("default_texture", "tubular")

    tags = f"{_BASE_TAGS} {meta['mood_tags']} {tex} {key.lower()} {scale.replace('_', '-')}".strip()
    desc = _BASE_DESCRIPTION + _PRESET_DESCRIPTION_TEMPLATE.format(
        name=name, texture=tex.capitalize(), key=key, scale_mode=scale.replace("_", " "),
        bpm=bpm, blurb=meta["blurb"],
    )

    return {
        "audio_filename": filename,
        "name":           f"{name} – Generative Bell Soundscape by Campana",
        "tags":           tags,
        "geotag":         "",
        "description":    desc,
        "license":        "Creative Commons 0",
        "pack_name":      "Generative Bells by Campana",
        "is_explicit":    0,
        "bst_category":   "m-m",
    }


def write_freesound_xlsx(rows: list, output: Path):
    import openpyxl
    from openpyxl.styles import Font, PatternFill, Alignment

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Freesound Bulk Describe"

    headers = ["audio_filename", "name", "tags", "geotag", "description",
               "license", "pack_name", "is_explicit", "bst_category"]
    widths  = [32, 52, 80, 12, 80, 22, 30, 12, 14]

    hdr_font = Font(name="Arial", bold=True, color="FFFFFF")
    hdr_fill = PatternFill("solid", start_color="2F5496")
    hdr_al   = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for col, (h, w) in enumerate(zip(headers, widths), 1):
        cell = ws.cell(row=1, column=col, value=h)
        cell.font = hdr_font; cell.fill = hdr_fill; cell.alignment = hdr_al
        ws.column_dimensions[cell.column_letter].width = w

    row_al  = Alignment(vertical="top", wrap_text=True)
    alt_fill = PatternFill("solid", start_color="EEF3FB")

    for i, row in enumerate(rows, 2):
        fill = alt_fill if i % 2 == 0 else None
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=i, column=col, value=row.get(h, ""))
            cell.font      = Font(name="Arial", size=10)
            cell.alignment = row_al
            if fill: cell.fill = fill

    ws.row_dimensions[1].height = 22
    for i in range(2, len(rows) + 2):
        ws.row_dimensions[i].height = 80

    ws.freeze_panes = "A2"
    wb.save(output)
    print(f"  📋 Freesound xlsx  →  {output}")


def list_presets():
    from engine.presets import PRESETS
    print(f"{'ID':<16} {'Name':<16} BPM   Key        Scale")
    print("─" * 60)
    for pid, p in PRESETS.items():
        print(f"{pid:<16} {p['name']:<16} {p.get('default_bpm','?'):<6}"
              f"{p.get('default_key','C'):<11}{p.get('default_scale_mode','minor')}")
    print(f"\n{len(PRESETS)} preset(s).")


def render_preset(preset_id: str, minutes: float, output: Path):
    from engine.web_server import _do_full_render, _parse_render_params
    from engine.presets import PRESETS

    preset = PRESETS.get(preset_id)
    if preset is None:
        sys.exit(f"Unknown preset '{preset_id}'. Use --list to see options.")

    p = _parse_render_params({
        "preset":     preset_id,
        "bpm":        preset["default_bpm"],
        "key":        preset.get("default_key", "C"),
        "reverb_room":      preset.get("default_reverb", 0.75),
        "reverb_damping":   preset.get("default_reverb_damping", 0.4),
        "reverb_width":     preset.get("default_reverb_width", 0.8),
        "reverb_wet":       preset.get("default_reverb_wet", 0.35),
        "decay_mult":       preset.get("default_decay", 1.4),
        "texture":          preset.get("default_texture", "tubular"),
        "beating":          preset.get("default_beating", 0.0),
        "strike_level":     preset.get("default_strike", 0.0),
        "attack_ms":        preset.get("default_attack_ms", 0.0),
        "humanize":         preset.get("default_humanize", 0.0),
        "density":          preset.get("default_density", 1.0),
        "octave_spread":    preset.get("default_octave_spread", 0.0),
        "base_octave_shift":preset.get("default_base_octave", 0),
        "time_scatter":     preset.get("default_time_scatter", 0.0),
        "delay_time":       preset.get("default_delay_time", 300),
        "delay_feedback":   preset.get("default_delay_feedback", 0.35),
        "delay_wet":        preset.get("default_delay_wet", 0.0),
        "shimmer":          preset.get("default_shimmer", 0.0),
        "scale_mode":       preset.get("default_scale_mode", "minor"),
        "seed_base":        42,
    })
    p["export_beats"] = minutes * p["bpm"]

    print(f"  🔔 {preset['name']:<14} {minutes:.0f} min @ {p['bpm']} BPM …", end="", flush=True)
    wav = _do_full_render(p)
    output.write_bytes(wav)
    dur = len(wav) / (48_000 * 2 * 2)
    print(f"  {dur/60:.1f} min  →  {output}  ({len(wav)/1e6:.1f} MB)")
    return output.name


def main():
    from engine.presets import PRESETS

    parser = argparse.ArgumentParser(description="Campana — generative bell synthesizer")
    parser.add_argument("--gui",       action="store_true", help="Launch web UI")
    parser.add_argument("--list",      action="store_true", help="List presets")
    parser.add_argument("--all",       action="store_true", help="Export all presets")
    parser.add_argument("--freesound", action="store_true", help="Generate Freesound bulk upload xlsx")
    parser.add_argument("--preset",    default="sera",
                        choices=list(PRESETS.keys()), help="Preset ID (default: sera)")
    parser.add_argument("--minutes",   type=float, default=2.0,
                        help="Export duration in minutes (default: 2)")
    parser.add_argument("--output",    type=Path, default=None,
                        help="Output WAV path (single preset only)")
    args = parser.parse_args()

    if args.list:
        list_presets()
        return

    if args.gui:
        try:
            from engine.web_server import launch_gui
        except ImportError as e:
            sys.exit(f"Web UI requires fastapi and uvicorn.\nError: {e}")
        launch_gui()
        return

    if args.all:
        print(f"Exporting all {len(PRESETS)} presets ({args.minutes:.0f} min each) → {EXPORT_DIR}/\n")
        rows = []
        for pid in PRESETS:
            fname = render_preset(pid, args.minutes, EXPORT_DIR / f"{pid}.wav")
            rows.append(_freesound_row(pid, fname, args.minutes))
        write_freesound_xlsx(rows, EXPORT_DIR / "freesound_bulk.xlsx")
        print("\nDone.")
    else:
        output = args.output or EXPORT_DIR / f"{args.preset}.wav"
        fname  = render_preset(args.preset, args.minutes, output)
        if args.freesound:
            rows = [_freesound_row(args.preset, fname, args.minutes)]
            write_freesound_xlsx(rows, output.parent / "freesound_bulk.xlsx")


if __name__ == "__main__":
    main()
